[build]
command = 'hugo'
publish = 'public'

[build.environment]
HUGO_VERSION = '0.146.7'

[context]
[context.branch-deploy]
command = 'hugo -F -b $DEPLOY_PRIME_URL'

[context.deploy-preview]
command = 'hugo -F -b $DEPLOY_PRIME_URL'

[context.production]
[context.production.environment]
HUGO_ENV = 'production'

[[headers]]
  for = "/index.xml"
  [headers.values]
    Content-Type = "application/rss+xml"

[[redirects]]
  from = "/index.xml"
  to = "/index.xml"
  status = 200    